# Generated by Django 3.2.12 on 2022-03-02 17:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220302_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preparation_steps',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
