# Generated by Django 3.2.12 on 2022-03-02 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_preparation_steps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='preparation_steps_is_html',
        ),
    ]
